# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "jackgao-thu"
repo_name: "nlp-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/nlp-arxiv-daily.json'
json_gitpage_path: './docs/nlp-arxiv-daily-web.json'
json_wechat_path: './docs/nlp-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LLM": 
        filters: ["LLM", "Large Langauge models", "Models for Natural Language"]
    "Attention":
        filters: ["Word Tokenization", "Attention Model", "Attention Mechanisms", "Attention Weight", "LoRA", "Low-rank", "Memory", "Multi-head", "Transformer", "Multimodel", "Reflection", "Distill", "Augment", "Knowledge"]
    "Deep Learning":
        filters: ["Deep Learning","Entity Recognition", "Transfer Learning", "Pre-trained", "Pretraining", "Weakly-supervised Learning", "Neural Reading Comprehension"]
    "Extraction":
        filters: ["Tagging", "Information Extraction", "Knowledge Graphs", "Entity Recognition", "Local Feature Matching", "Text Classification"]
    "In-context Learning":
        filters: ["In-context Learning", "CoT", "Zero-shot", "Few-shot"]

# keywords:
#     "SLAM": 
#         filters: ["SLAM", "Visual Odometry"]
#     "SFM":
#         filters: ["SFM", "Structure from Motion"]
#     "Visual Localization":
#         filters: ["Visual Localization","Camera Localization",
#                   "Camera Re-localisation","Loop Closure Detection",
#                   "visual place recognition","image retrieval"]
#     "Keypoint Detection":
#         filters: ["Keypoint Detection", "Feature Descriptor"]
#     "Image Matching":
#         filters: ["Image Matching", "Keypoint Matching", 
#                   "Line Segment Detection", "Local Feature Matching"]
#     "NeRF":
#         filters: ["NeRF"]